name = "pokky-guild-hub"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding       = "DB"
database_name = "guild-auth"
database_id   = "0c19c5fc-8c9d-4195-9a89-e32ec4a37daf"